version: "3.6"
services:
  dokku:
    image: dokku/dokku
    environment:
      - DOKKU_HOSTNAME=${DOKKU_HOSTNAME}
      - DOKKU_HOST_ROOT=${DOKKU_HOST_ROOT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/dokku
    ports:
      - "8080:80"
      - "8022:22"
      - "8443:443"
